# Site settings
title: Solace Samples C
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-c"
repository: https://github.com/SolaceSamples/solace-samples-c

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-downloads: //solace.com/downloads/
links-community: //solace.com/support/
links-solaceCloud-setup: //solace.com/cloud/#pageblock_36103
docs-core-concepts: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-api-ref: //docs.solace.com/API-Developer-Online-Ref-Documentation/c/index.html
docs-api-ref-enumerations: //docs.solace.com/API-Developer-Online-Ref-Documentation/c/globals_enum.html
docs-endpoints: https://docs.solace.com/PubSub-Basics/Endpoints.htm
docs-gm-rr: //docs.solace.com/Solace-Messaging-APIs/Request-Reply-Messaging.htm
docs-topic-queue: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-replay-use-cases: //docs.solace.com/Configuring-and-Managing/Message-Replay.htm
docs-replay-cli-config: //docs.solace.com/Configuring-and-Managing/Msg-Replay-Config.htm
docs-psplus-manager: //docs.solace.com/Solace-PubSub-Manager/PubSub-Manager-Overview.htm
docs-semp-api: //docs.solace.com/SEMP/Using-SEMP.htm